- src/components/Menu/MenuLinks.ts
- src/content/get-started.mdx
- src/data/generic.tsx
- getStarted 1차 번역 완
- 오역이거나, 기타 어색한 번역 투 지적 환영
> Docs: getStarted 및 관련 부분 번역

- src/content/docs/useform/getvalues.mdx
- Docs getValues 번역. 
- 이슈 링크(#14, #7)
> Docs: getValues.mdx

- src/content/docs/useform/getfieldstate.mdx
- getFieldstate 번역 작업
- 연결 이슈 링크(#7 , #18)
> Docs: getFieldstate.mdx

- src/content/docs/useform/form.mdx
- docs: form.mdx 번역
- 관련이슈(#7, #16)
> docs:form.mdx

- src/content/docs/useform/handlesubmit.mdx
- handleSubmit 문서 번역 작업
- 관련 이슈 링크(#7 , #20 )
> Docs: handleSubmit.mdx

- src/content/docs/useform/trigger.mdx
- trigger.mdx docs 번역
- 관련 이슈 링크(#7 , #30 )
> docs:trigger.mdx

- src/components/useForm/SetValue.tsx
- src/data/api.tsx
> feat: setValue 번역

- src/content/docs/useformcontext.mdx
- useFormContext를 번역했습니다. 
close: #64
> docs: useFormContext 번역 

- src/content/docs/formprovider.mdx
- FormProvider를 번역했습니다. 
close: #65
> docs: FormProvider 번역

- package.json
- src/content/docs/usewatch.mdx
- useWatch를 번역했습니다. 
- 렌더 단계(render phase)를 병기처리 했습니다. 
- props는 props 원문으로 작성했습니다.
close: #66
> feat: useWatch 번역

- src/components/ApiGallery.tsx
> docs: api 개요 번역

- src/components/UseFormState.tsx
- useFormState 번역 
- 관련 이슈: #67 , #61
> docs: useFormState 번역

- src/data/home.tsx
- 이 PR은  #82 이슈를 해결합니다.
- `src/data/home.tsx -> slogan` 이 "밸리데이션" 으로 번역되어 있던 것을 "유효성 검사" 로 수정합니다.
> fix: home "밸리데이션" 수정

- src/components/UseController.tsx
- src/components/UseControllerContent.tsx
- src/components/UseControllerMethods.tsx
- src/components/codeExamples/useController.ts
- src/data/api.tsx
> docs: useController 번역

- src/components/codeExamples/useControllerCheckboxes.ts
- src/components/useForm/FormState.tsx
- src/content/docs/usecontroller/controller.mdx
- src/content/docs/useform/watch.mdx
- src/data/api.tsx
- register, formState, watch, useController, Controller에서 번역 안된 부분을 추가 번역하였습니다.
> 번역 안된 부분 추가 번역

- .github/workflows/sync-src-excluded-translate.yml
- package.json
- pnpm-lock.yaml
- src/pages/_app.tsx
- src/pages/providers/PostHogProvider.tsx
- _app.tsx에 PosthogProvider 추가
> Feat: post hog 추가

- src/content/get-started.mdx
- 관련 이슈 
https://github.com/hamsurang/react-ko-form/issues/106 
https://github.com/hamsurang/react-ko-form/issues/85
> docs: :recycle: get-started-mdx shadcn/ui 추가

- package.json
- src/content/docs/useform/register.mdx
> feat: register mdx  번역

- src/content/docs/useform/seterror.mdx
> docs: 예제 내부 의존성 배열 수정

- src/content/docs/useformcontext.mdx
> docs: useformcontext.mdx SelectNav 추가 및 기타 예제 코드 추가

- src/content/docs/useform/handlesubmit.mdx
> docs: 예제 내부 return 문 추가 및 기타 SubmitErrorHandler, 불 필요한 부분 삭제

- src/content/docs/useform/watch.mdx
> docs: docs 구성 및 내용 변경에 따른 번역 최신화

- package.json
- src/components/Menu/MenuLinks.ts
- src/content/advanced-usage.mdx
close: #153 
- 단계별 폼(Wizard Form)
- 라우트(routes)
- 스토어(store)
- 옵셔널 체이닝(Optional Chaining)
- 가상화된(virtualized)
> feat: advanced-usage.mdx 번역

- .github/workflows/compare-src.yml
- 기존 비교 생성하는 pr의 yml에서 추가로 이슈도 자동 생성하는 로직 추가했습니다.
> Feat: issue generator

- src/content/docs/useform/trigger.mdx
> docs: trigger mdx codebox 수정

- src/content/docs/usewatch.mdx
> docs: useWatch codebox 수정
